### PR TITLE
Added confetti animation when user creates a post

### LINKED ISSUE #34: Create a Confetti animation when user uploads a post
react-confetti package - https://www.npmjs.com/package/react-confetti

### PR DESCRIPTION
**Pull request by shivam1317**
This fixes #34

### CODE REVIEW

**Comment by adarshanand67** [comment]
Use this 2 lines in Confettis.js
const width = window.innerWidth;
  const height = window.innerHeight;

And the save button is not working when user clicks it?

**Comment by adarshanand67** [comment]
Confettis are working but not the saving button kindly look into it!

**Comment by adarshanand67** [comment]
@shivam1317 resolve merge conflicts keep the change of the main file

**Comment by shivam1317** [comment]
@adarshanand67 Check now

**Comment by adarshanand67** [comment]
Good!

**Pull request merged**
