### PR TITLE
Image not loading onClick when searching #61

### PR DESCRIPTION
**Pull request by Hrx4**
Now the search button is working fine.

### CODE REVIEW

**Comment by adarshanand67** [comment]
Kindly resolve conflicts before continuing

**Comment by adarshanand67** [comment]
Rest looks good

**Comment by adarshanand67** [comment]
Pull data before making changes, project structure has changed!

**Comment by Hrx4** [comment]
Can you please tell me again what should i do? i don't get your point ;(

**Comment by Hrx4** [comment]
Actually the resolve conflict button isn't clickable ;(

**Comment by adarshanand67** [comment]
> 
> Can you please tell me again what should i do? i don't get your point ;(  

Like the project has merge conflicts that need to be solved.

And the commit hooks are not working

**Comment by Hrx4** [comment]
Is the PR close? should i make a new PR?

**Pull request closed without merging**
