### PR TITLE
Delete favicon.png and replacing with new one

### PR DESCRIPTION
**Pull request by abhrajit117**
favicon

### CODE REVIEW

**Comment by adarshanand67** [comment]
Kindly add new files, you just removed the original files ig

**Comment by abhrajit117** [comment]
give me access to upload . upload is disabled!

**Comment by adarshanand67** [comment]
I think just edit the files in your branch and send pr, I gave you access (ig you mean assigning the PR)

**Comment by adarshanand67** [comment]
Just send me all the assets i would replace @abhrajit117

**Comment by abhrajit117** [comment]
hi, there I am attaching the favicon file here. sorry for the delay

**Comment by adarshanand67** [comment]
I still cant see the files

**Pull request closed without merging**
