### PR TITLE
testing pre-commit

### PR DESCRIPTION
**Pull request by Laxmankohar**
image

### CODE REVIEW

**Comment by Laxmankohar** [comment]
why i am not able to commit all the files?
image

**Comment by adarshanand67** [comment]
Can you do in inside the frontend folder?
Instead of creating it in root dir

**Comment by adarshanand67** [comment]
I know husky has to be in root dir but if possible can you try this?

**Comment by adarshanand67** [comment]
I am not able to commit anything when doing this

**Comment by adarshanand67** [comment]
image
Gives me some lint errors. Does it work fine from your end?

**Comment by Laxmankohar** [comment]
> image Gives me some lint errors. Does it work fine from your end?

Yes, it was working fine from my end but turned off the error from rules inside eslintrc.json file

**Comment by adarshanand67** [comment]
Can you update eslintrc.json file and commit?

**Comment by Laxmankohar** [comment]
Bro, now check it.. Actually i have deleted all the files from root directory  inorder to setup for frontend only.

**Comment by adarshanand67** [comment]
Still having errors 
image

**Comment by Laxmankohar** [comment]
Bro, where you want to setup the pre-commit functionality? in frontend only or in whole code? above commit is setup for whole code.

**Comment by adarshanand67** [comment]
You can have it for the whole codebase, but frontend is also fine

**Comment by adarshanand67** [comment]
Can you show me a demo video where this works?

**Comment by adarshanand67** [comment]
> Bro, where you want to setup the pre-commit functionality? in frontend only or in whole code? above commit is setup for whole code.

You did it correctly , the thing is eslint was throwing errors.

**Comment by Laxmankohar** [comment]
> > Bro, where you want to setup the pre-commit functionality? in frontend only or in whole code? above commit is setup for whole code.
> 
> You did it correctly , the thing is eslint was throwing errors.

Can you please share the ss?

**Comment by adarshanand67** [comment]
> > > Bro, where you want to setup the pre-commit functionality? in frontend only or in whole code? above commit is setup for whole code.
> > 
> > 
> > You did it correctly , the thing is eslint was throwing errors.
> 
> Can you please share the ss?

This was the ss - 
https://user-images.githubusercontent.com/73928744/221919463-fcd6c377-24a5-423e-8d8f-8852117ccbdb.png

**Comment by Laxmankohar** [comment]
bro add the difficulty level tag

**Pull request merged**
