### PR TITLE
created pwa for the website

### PR DESCRIPTION
**Pull request by Awesomeasma**

### CODE REVIEW

**Comment by adarshanand67** [comment]
Can you bring back previous favicon?

**Comment by adarshanand67** [comment]
Also can you explain how did you solve this issue through a video?

**Comment by Awesomeasma** [comment]
> It seems that you have simply copy pasted code, how does this line work image

I don't have any prior understanding about pwa. I have followed the steps shown in the video that you provided. I am trying to resolve it now.

**Comment by Awesomeasma** [comment]
Do you want me to close this pull request for now ?

**Comment by adarshanand67** [comment]
Yes

**Pull request closed without merging**
