### PR TITLE
added cancel button

### PR DESCRIPTION
**Pull request by suryanshsoni120**

### CODE REVIEW

**Comment by adarshanand67** [comment]
image
Cancel button is ok also add icons in input box and send ss

**Comment by adarshanand67** [comment]
@suryanshsoni120 Add icons in the text input asap

**Comment by adarshanand67** [comment]
Use https://icon-sets.iconify.design/

**Comment by adarshanand67** [comment]
What happened?

**Comment by suryanshsoni120** [comment]
Have done the changes and made another PR. Sorry for this

**Pull request closed without merging**
